### ISSUE TITLE
You are not on http://yeoman.io/generators/ for some reason

### ISSUE THREAD

**Issue by skfd** [belen-albeza/generator-gamejam#2]

**Comment by belen-albeza** [comment]
Thanks for the heads up, I'm looking into it :+1:

**Comment by belen-albeza** [comment]
![screen shot 2015-08-16 at 15 43 49](https://cloud.githubusercontent.com/assets/63681/9293503/cdd74bca-442d-11e5-9553-319dc1bea410.png)

Fixed :)
