### ISSUE TITLE
phaser.min not copied to distr js lib folder

### ISSUE THREAD

**Issue by geremyAB** [belen-albeza/generator-gamejam#3]
Hi, When using generator gamejan, always send message of Warning for deprecated or updete graceful and lodash, and maybe this should be the reason for why gulp build doesn´t copy phaser.min.js from node_modules to dist/js/

npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

The fact is that I can not see the awesome game created because console shows message 404 phaser.min not found. **ReferenceError: Phaser is not defined** bundle.js

**Comment by belen-albeza** [comment]
Thanks for the report! The `ReferenceError` has been fixed in the 1.2.2 release.
